---

on:
  release:
    tags:
      - '*'
    types: [published]


jobs:
  build:
    name: Build phase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static_files
          path: |
            static

