---

on:
  #push:
  release:
    tags:
      - '*'
    types: [published]


jobs:
  build:
    name: Build phase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Asset
        run: echo ::set-output name=asset::${GITHUB_REF#refs/tags/}
        #run: echo ::set-output name=asset::${GITHUB_REF#refs/heads/}
        id: asset

      - name: Package release
        run: |
          tar -czf static_files-${{ steps.asset.outputs.asset }}.tgz static

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            static_files-${{ steps.asset.outputs.asset }}.tgz
