---
name: Main Dispatch

on:
  workflow_dispatch:
    inputs:
      foobar:
        description: 'my Foobar'
        required: true
        default: 'myBar'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Hello World example
      - name: Hello World
        run: |
          touch HelloWorld
          echo "Hello world ${{ github.event.inputs.foobar }}" >> HelloWorld
      # Hello World example
      - name: Hello World 2
        run: |
          touch HelloWorld2
          echo "Hello world ${{ github.event.inputs.foobar }}" >> HelloWorld2
